-- Up Migration
-- prompt_pool: a shared pool of short prompt seeds that users can vote on.
-- The hourly generator picks the top-voted unused prompt and expands it via
-- Gemini before sending to an image model. Source distinguishes seed prompts
-- (auto-generated by scripts/seed-prompts.js) from user submissions.
--
-- To apply manually:
--   psql "$DATABASE_URL" -f migrations/1000000009000_prompt-pool.sql
-- or via the Supabase SQL editor. node-pg-migrate also picks this up under
-- npm run db:migrate:up.

create table if not exists prompt_pool (
  id uuid primary key default gen_random_uuid(),
  text text not null unique,
  votes integer not null default 0,
  created_at timestamptz not null default now(),
  used_at timestamptz,
  source text not null default 'seed'
);

create index if not exists idx_prompt_pool_votes on prompt_pool(votes desc);
create index if not exists idx_prompt_pool_used on prompt_pool(used_at);

-- prompt_votes: per-IP vote ledger so we can rate-limit 1 vote per IP per
-- prompt per hour and have a record of who voted for what.
create table if not exists prompt_votes (
  id uuid primary key default gen_random_uuid(),
  prompt_id uuid not null references prompt_pool(id) on delete cascade,
  ip_hash text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_prompt_votes_prompt_ip
  on prompt_votes(prompt_id, ip_hash, created_at desc);

-- Atomic upvote RPC: rejects same-IP-within-an-hour, then increments.
create or replace function vote_on_prompt(p_prompt_id uuid, p_ip_hash text)
returns table(new_votes integer) language plpgsql as $$
declare
  recent_count integer;
  updated_votes integer;
begin
  select count(*) into recent_count
  from prompt_votes
  where prompt_id = p_prompt_id
    and ip_hash = p_ip_hash
    and created_at > now() - interval '1 hour';

  if recent_count > 0 then
    raise exception 'rate_limited' using errcode = 'P0001';
  end if;

  insert into prompt_votes (prompt_id, ip_hash) values (p_prompt_id, p_ip_hash);

  update prompt_pool set votes = votes + 1
    where id = p_prompt_id
    returning votes into updated_votes;

  if updated_votes is null then
    raise exception 'prompt_not_found' using errcode = 'P0002';
  end if;

  return query select updated_votes;
end;
$$;

-- Hourly image gets the short + expanded prompt stored alongside the image
-- reference so we can show users what they voted for and what was actually
-- sent to the model.
alter table hourly_images add column if not exists short_prompt text;
alter table hourly_images add column if not exists expanded_prompt text;

-- Down Migration
alter table hourly_images drop column if exists expanded_prompt;
alter table hourly_images drop column if exists short_prompt;
drop function if exists vote_on_prompt(uuid, text);
drop index if exists idx_prompt_votes_prompt_ip;
drop table if exists prompt_votes;
drop index if exists idx_prompt_pool_used;
drop index if exists idx_prompt_pool_votes;
drop table if exists prompt_pool;
